### ISSUE TITLE
Issue with GET /MultisigContract/{address}

### ISSUE THREAD

**Issue by simontakouridis** [idena-network/idena-indexer-api#2]
Consistently receiving an error with the GET /MultisigContract/{address} enpoint, e.g.:

Request:
curl -X GET "https://api.idena.io/api/MultisigContract/0x4cDe91b54a124B766FD2d8D62529F4e8B9fc4c2A" -H "accept: application/json"

Response:
{"error":{"message":"unable to load indexer data"}}

cc @mbidenaio

**Comment by mbidenaio** [comment]
Fixed. Thanks for the report.
